fixtures:
  repositories:
    "stdlib": 
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      ref: 4.12.0
    "concat": "https://github.com/puppetlabs/puppetlabs-concat"
    "logrotate" : "https://github.com/icann-dns/puppet-logrotate"
  symlinks:
    "nsd": "#{source_dir}"
