fixtures:
  repositories:
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib"
    "concat": "https://github.com/puppetlabs/puppetlabs-concat"
    "logrotate" : "https://github.com/icann-dns/puppet-logrotate"
  symlinks:
    "nsd": "#{source_dir}"
