fixtures:
  repositories:
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib"
    "concat": "https://github.com/puppetlabs/puppetlabs-concat"
    "logrotate" : "https://github.com/b4ldr/puppet-logrotate"
  symlinks:
    "ssh": "#{source_dir}"
