fixtures:
  repositories:
    tea: 
      repo: https://github.com/icann-dns/puppet-tea
      ref: v0.2.7
    "stdlib": 
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      ref: 4.17.0
    "concat": "https://github.com/puppetlabs/puppetlabs-concat"
    "logrotate" : "https://github.com/icann-dns/puppet-logrotate"
  symlinks:
    "nsd": "#{source_dir}"
